// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)
const fs = require('fs');
const path = require('path');

const docsJsonPath = path.resolve(__dirname, './docs.json');

let docs = []
try {
  // 读取 docs.json 文件
  const rawData = fs.readFileSync(docsJsonPath, 'utf8');
  docs = JSON.parse(rawData);

  // 转换为 Docusaurus 侧边栏格式
  const sidebarItems = docs.map(item => ({
    type: 'doc',
    id: item.slug,
    label: item.title,
  }));
  docs = sidebarItems;
  // 构建完整的 sidebars 对象

} catch (error) {
  console.error('Error:', error);
}


/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // tutorialSidebar: [
  //   'intro',
  //   'hello',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ],
  'docs': docs
};

export default sidebars;
