on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

# 配置要部署到的环境
concurrency:
  group: "pages"
  cancel-in-progress: false

# 默认为部署到 github pages 环境
environment:
  name: github-pages
  url: ${{ steps.deployment.outputs.page_url }}

jobs:
  feishu-pages:
    name: Feishu Pages Export
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: dist/.cache
          key: cache-dist
      - name: Exporting
        env:
          FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          FEISHU_SPACE_ID: ${{ secrets.FEISHU_SPACE_ID }}
        uses: longbridge/feishu-pages@main
      - name: Build Pages
        run: |
          cp -r dist/docs ./docs
          cp dist/docs.json ./    
          yarn
          yarn build
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          # 明确指定启用 GitHub Pages
          enablement: true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./build"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4